#!/bin/bash
docker buildx create --name multiarch --use
docker buildx build --push --platform linux/arm64,linux/amd64 . -t 2martens/terraform-drone-plugin:1.6.2 -t 2martens/terraform-drone-plugin:latest
